name: Linting

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:

  golangci-lint:
    name: Linting
    strategy:
      matrix:
        go-version: [ stable, oldstable ]
        os: [blacksmith-4vcpu-ubuntu-2404, macos-latest, windows-latest]
    env:
      GO_VERSION: stable
      GOLANGCI_LINT_VERSION: v1.59
      CGO_ENABLED: 0
    runs-on: ${{ matrix.os }}

    steps:
      - if: ${{ matrix.os == 'windows-latest' }} # https://github.com/actions/checkout/issues/135
        run: |
          git config --global core.eol lf
          git config --global core.autocrlf input
      - uses: actions/checkout@v4
      - uses: useblacksmith/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: useblacksmith/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
