name: Tests and Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:

  tests:
    name: Tests
    strategy:
      matrix:
        go-version: [ stable, oldstable ]
        os: [blacksmith-4vcpu-ubuntu-2404, macos-latest, windows-latest]
    env:
      CGO_ENABLED: 1
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: useblacksmith/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check and get dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: Test
        run: go test -v -race ./...

  build:
    name: Build
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - uses: useblacksmith/setup-go@v6
        with:
          go-version: stable
      - name: compile for all supported GOOS/GOARCH
        run: ./build.sh
